namespace:
  name: sandbox
 
service:
  port: 4111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP  

image:
  repository: ahmednoureldeen/techtrends 
  tag: latest
  pullPolicy: IfNotPresent

replicaCount: 1

containerPort: 3111

resources:        
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

livenessProbePath: /healthz
        
readinessProbePath: /healthz       